# ImageNet VID specific configuration for MVP detector

# Model settings
model:
  id: "google/owlv2-large-patch14-ensemble"
  device: "cuda"
  confidence_threshold: 0.5

# Processing settings optimized for ImageNet VID
processing:
  single_class_fail_limit: 2
  area_scale_threshold: 2.0
  extract_frames: true
  force_detection_interval: 5  # Force detection every N frames if no detections

# Motion vector settings
motion_vector:
  min_displacement: 1.0
  translation_std_threshold: 1.0
  scaling_std_threshold: 0.1
  grid_size: 3  # 3x3 grid for motion analysis

# Evaluation settings
evaluation:
  iou_thresholds: [0.2, 0.3, 0.5]
  iou_range: [0.5, 0.95]
  num_classes: 30

# ImageNet VID specific paths
paths:
  video_root: "/path/to/ILSVRC2015/Data/VID/snippets/val"
  motion_vector_root: "/path/to/ILSVRC2015/mvs/val"
  output_root: "/path/to/results"
  ground_truth_root: "/path/to/ILSVRC2015/yolo_dataset/labels/val"

# Dataset specific settings
dataset:
  name: "ImageNet VID"
  split: "val"
  num_videos: 555  # Number of validation videos
  classes: 30
